name: publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: erlang:27-alpine
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash \
                              musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: work around for permission issue
      run: |
           git config --global --add safe.directory /__w/eradius/eradius
    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           rebar3 edoc
           rebar3 hex publish -r hexpm --yes
