name: publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    container:
      image: erlang:23.2.5.0-alpine
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash \
                              musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib
    - uses: actions/checkout@v3
    - name: work around for permission issue
      run: |
           git config --global --add safe.directory /__w/eradius/eradius
    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           rebar3 edoc
           rebar3 hex publish -r hexpm --yes
