name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [27.3, 28, 29]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add zstd
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Build
      run: rebar3 compile
    - name: Run tests
      run: |
           export ERL_AFLAGS="+pc unicode"
           rebar3 do xref, ct
           rebar3 as dialyzer dialyzer
    - name: Tar Test Output
      if: ${{ always() }}
      run: tar -cf - _build/test/logs/ | zstd -15 -o ct-logs-${{ matrix.otp }}.tar.zst
    - name: Archive Test Output
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-output-${{ matrix.otp }}
        path: ct-logs-${{ matrix.otp }}.tar.xz

  slack:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Slack notification
      uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e # v3.19.0
      with:
        author_name: "GitHub Actions"
        username: ${{ github.event.repository.name }}
        icon_emoji: ':octocat:'
        fields: repo, message, ref, commit, author, action, eventName, workflow, job, took
        status: ${{ needs.test.result }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
